name: Build My Fork
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive # Crucial for C++ projects

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild YourSolutionName.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: my-build-files
          path: |
            **/Release/*.exe
            **/Release/*.dll
